### ISSUE TITLE
[1.10.2] net.minecraftforge.fml.common.LoaderExceptionModCrash

### ISSUE THREAD

**Issue by Thiana** [cubex2/customstuff4#1]
I attempted to use some of the Railcraft blocks with CS4 (I love the blocks but don't like minecarts).

First attempt was using a basic block with subtypes and modifying the RC blockstate files to match the created block. That crashed (see http://openeye.openmods.info/crashes/c729de770214b2191aa1355e9cccbed5).

The second attempt I split the textures files into individual textures then made CS4 entries and blockstates to match them. The result was a very similar crash (http://openeye.openmods.info/crashes/10c75054ace116e6bdd623227453be63).

I'm attaching the configuration I used for the second attempt.

[thianacs4.zip](https://github.com/cubex2/customstuff4/files/976268/thianacs4.zip)

Am I doing something incorrectly? Thanks.

**Comment by cubex2** [comment]
That was actually a bug that doesn't occur in my dev environment. Should be fixed now.
