### ISSUE TITLE
[Potential Bug] Stair model crash

### ISSUE THREAD

**Issue by Titus-Armillius** [cubex2/customstuff4#12]
I' am sorry for posting so many issues, but I find this the best way of communication for these kinds of things; if you want me to post somewhere else, please tell me.

Crash Report: https://pastebin.com/ecDN0n2U

Json code: https://pastebin.com/GvGFXKHY

I tried having the Modelstate reference the 'custom_assets:blocka' initially, but that produced the same crash. I double checked my model/blockstate files, and they are correct. So I think it might be the case that I need to somehow specify the stair model variants such as 'blocka_inner_stairs.json'. I don't see the reason why though, considering that the example code only references the primary solid block which I already tried. BTW my blockstate file is formatted exactly like one in the examplemod folder, except that it references the block models in my CustomStuff4 mod folder.

**Comment by cubex2** [comment]
'custom_assets:blocka' for the modelState should be correct.
The crash might be caused by another mod. I can't think of any way CS4 can cause that crash. The report has BetterGrass in the trace, but that alone shouldn't cause it as I've tested that and it works fine.
