### ISSUE TITLE
[Question/Request] Ability to use resourcepack .json models

### ISSUE THREAD

**Issue by GazbonicAcid** [cubex2/customstuff4#14]
If it is not already in the mod,
I would like to request the ability to use resource-pack .json block models as my blocks' from this mod's model from within my cs4 json's config.
More specifically, the resource-pack .json block models exported from Chisels & Bits.

**Comment by cubex2** [comment]
Are those models just regular block models are is there something special to them? If it's the former you can just put them into the models folder of your cs4 mod and use them like any other model.
