### ISSUE TITLE
[Bug?] Changing the block material type does not seem to have an effect on its properties

### ISSUE THREAD

**Issue by Titus-Armillius** [cubex2/customstuff4#16]

**Comment by cubex2** [comment]
What effects on the properties are you expecting from the block material? I don't think it's supposed to have an effect on most of a block's properties.

**Comment by Titus-Armillius** [comment]
@cubex2 I tried changing a blocks material to 'grass', expecting it to then exhibit the properties of grass; namely that of it being able to support tall grass, flowers, etc.

**Comment by cubex2** [comment]
Setting the material to grass will pretty much just change the block's color on a map. 

I'm going to add a property to specifiy what plants can be placed on a block.

**Comment by cubex2** [comment]
A sustainedPlants attribute will be included in the next version.
