### ISSUE TITLE
Block Placement oddity

### ISSUE THREAD

**Issue by Thiana** [cubex2/customstuff4#2]
When using custom blocks with CS4 1.10.2-0.0.2 there is a rather interesting bug. I can freely place the defined blocks as long as I don't try place the block onto a block created by CS4.

To replicate, try to create a pillar of any CS4 defined block. You'll get the first block but nothing higher.

Thanks.

**Comment by cubex2** [comment]
Fixed

**Comment by Thiana** [comment]
Will you be pushing the fix to 1.10.2?

**Comment by cubex2** [comment]
I'm going to update the 1.10.2 version during the next few days.
