### ISSUE TITLE
Problem with defining directional blocks...

### ISSUE THREAD

**Issue by MBelhardi** [cubex2/customstuff4#20]
Hello, I'm trying to create a directional block. I use this the wiki, and also use the example. When I use the example, the blocks are created correctly, but the textures for the blocks are missing, as items are displayed correctly.
But when I try to create my own blocks, Minecraft throws me out each time with  an error message:
```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dead World (dead_world)

```
[crash-2017-08-06_00.19.33-client.txt](https://github.com/cubex2/customstuff4/files/1202716/crash-2017-08-06_00.19.33-client.txt)
[latest.log.txt](https://github.com/cubex2/customstuff4/files/1202720/latest.log.txt)
[dead_world.zip](https://github.com/cubex2/customstuff4/files/1202719/dead_world.zip)

**Comment by cubex2** [comment]
Your blockstate file should be called directional.json as that's the id of the block. You also need to remove the additional ',' after the hardness line.

**Comment by MBelhardi** [comment]
Ok, so I overlooked that the ID is also the name of the blockstates-file and the comma was just a slip of the pen... so far with the problems, you corrected, with your message ... But, that does not solve the problem, that I can not create a single block, so I always have to use "subtypes", although I would not want that, because only so Minecraft will start without crash. But this can not be the solution to the problem.
this is the corrected and changed version:
[dead_world.zip](https://github.com/cubex2/customstuff4/files/1203162/dead_world.zip)

**Comment by cubex2** [comment]
If you don't use the subtype attribute you also must not include 'subtype=subtype0' in the blockstate file. There is also a bug that crashes the game if you create a orientable block without subtypes that I have fixed now.
