### ISSUE TITLE
Problems like before the update....

### ISSUE THREAD

**Issue by MBelhardi** [cubex2/customstuff4#22]
Hello, I think you know what I want to say. The Problem is the exact same as before, when I try to make a block, and don't define subtypes, minecraft don't want to start (kicks me out while in startscreen, not even in the menu at that time).
But this time, when I try to place a block, after I defined the subtypes, minecraft crashes:
```
The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
```
[latest.log.txt](https://github.com/cubex2/customstuff4/files/1212446/latest.log.txt)
[crash-2017-08-09_20.13.37-client.txt](https://github.com/cubex2/customstuff4/files/1212448/crash-2017-08-09_20.13.37-client.txt)

**Comment by MBelhardi** [comment]
I'm sorry to say that part one of this isssue was a false alarm, after removing the "cs4mod"-folder, and changing the json-files, like the new examples, this problem is fixed.
But as a said, I can't place the created block, I've tried it so far only with the directional blocks, but I will test it with other blocks, and will tell you they also can't be placed.; 
```
The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
```
[latest.log_new.txt](https://github.com/cubex2/customstuff4/files/1212710/latest.log_new.txt)
[crash-2017-08-09_21.56.56-client.txt](https://github.com/cubex2/customstuff4/files/1212711/crash-2017-08-09_21.56.56-client.txt)

**Comment by cubex2** [comment]
Uploaded a fix for these issues.
