### ISSUE TITLE
transparent texture near stairs

### ISSUE THREAD

**Issue by MBelhardi** [cubex2/customstuff4#23]
when I place a stair near a full block, one side of the full block becomes tranparent... (latest update) Tested with created blocks and with vanilla blocks.
![2017-08-10_10 20 17](https://user-images.githubusercontent.com/30601633/29161216-af86673c-7db5-11e7-8172-b9ba44cd2017.png)

**Comment by cubex2** [comment]
Will be fixed in the next update. You can temporarily fix this yourself by setting isFullCube and isOpaqueCube to false for the stair block.
