### ISSUE TITLE
[question] dont understand the "modelState"-tag within your stair-example

### ISSUE THREAD

**Issue by MBelhardi** [cubex2/customstuff4#26]
Hello, I found in your stair-example this tag, that seems to make no sense:
```
          "modelState": {
            "block": "minecraft:log",
            "properties": {
              "variant": "spruce"
            }
          },
```
I mean you define a stair, youve given it the blockstate by the "id", and give it it's item-texture by "itemModel", why would you define "modelState" as a spruce log? It absolutely makes no sense, I was going through the wiki and couldn't find any reference to this tag. I also tried to remove this tag, but than minecraft crashes.
```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dead World (dead_world)
```
---
also not related to this question, a little bug I found: the item of directional blocks won't be shown in waila and hwyla, while otherwise no problem. Means, they are shown as item correct, as block correct, and even JEI show them correct, only waila shows the missing texture for them, all other blocks I testet so far, were shown by waila correct, no matter if it was stair, slabs, fence or normal blocks. Also wenn I try to copy the block (don't have it in the inventory, an click on it with the middle mouse button in creative) then the block will shown as missing texture.
![2017-08-10_19 53 40](https://user-images.githubusercontent.com/30601633/29184174-9d688d46-7e05-11e7-8013-4a7ce52349fa.png)

**Comment by cubex2** [comment]
I must have missed to add the modelState attribute to the wiki. I've added some information now.
The problem with waila will be fixed in the next update.
