### ISSUE TITLE
idk if i did something wrong or there is a problem with the mod. 

### ISSUE THREAD

**Issue by Varg95** [cubex2/customstuff4#28]
https://pastebin.com/nWupzPrb here is a crash report

**Comment by cubex2** [comment]
It seems like you're setting the amount of a block's drop like this `[5]`. However if you only specify one value it should just be `5`. The notation with [] is required if you specify a range like this: `[1,5]`

**Comment by Varg95** [comment]
changed it but still getting a crash https://pastebin.com/HJcSuQ7w sorry for bothering you so much...

**Comment by cubex2** [comment]
Seems like you're missing a closing }.

**Comment by Varg95** [comment]
i started over and now it does work thanks for the help.
