### ISSUE TITLE
Incorrect inventory textures for blocks

### ISSUE THREAD

**Issue by Thiana** [cubex2/customstuff4#3]
For some reason all custom blocks are given a stick texture in inventory instead of the block texture. The blocks do have the correct textures when placed in world. 

An example of the blockstate json is:
```
{
	"forge_marker": 1,
	"defaults": {
		"textures": {
			"all": "thianacs4:blocks/railcraft_bleachedbone_1"
		},	
		"transform": "forge:default-block",
		"model": "cube_all"
	},
	"variants": {
		"normal": [{}],
		"inventory": [{}]
	}
}
```

This is using  CS4 1.10.2-0.0.2. Thanks :)

**Comment by cubex2** [comment]
Have you set the item model attribute of the blocks?

**Comment by Thiana** [comment]
I was under the impression from reading about the forge extensions and viewing some examples that the extra model file wasn't needed when you used the blockstate with transform and inventory variant set. I've changed it to use the extra model file and set the itemModel.
