### ISSUE TITLE
I cant make the worldgen script work. Can you help me?

### ISSUE THREAD

**Issue by vpontin** [cubex2/customstuff4#30]
[This one](https://github.com/vicocraft/cs4claygen).

When i put this mod in my minecraft instance, no clay generates.

Using customstuff4-1.12.1-0.4.0, MC 1,12.1 and Forge b2474

**Comment by cubex2** [comment]
Is the worldgen supposed to only replace granite as you've set targetMeta to 1?

**Comment by vpontin** [comment]
Sorry for that, it was my fault. Removed the targetmeta and now it generate - very few veins, but generate. Thanks!
