### ISSUE TITLE
Recipe Problem with CraftTweaker

### ISSUE THREAD

**Issue by Sixdd6** [cubex2/customstuff4#34]
So I created an item with damage using custom stuff 0.4.0 on MC 1.12.2. I'm trying to create most of my recipes with crafttweaker because I find it easier than having to restart minecraft a bunch of times.

The problem is that the item is not acting as if it has a damage value when I craft with it. I created a tool item to give flour when crafted with wheat but the tool just disappears when I craft the flour. 

Here is the item code that I'm using: https://gist.github.com/Sixdd6/f98397667008ad02125d7b7208757cb5
And here is the crafttweaker script I'm using: https://gist.github.com/Sixdd6/a19438fa85986da921893cb010d2ae4f

Is it not working to set a damage for a simple item?

**Comment by cubex2** [comment]
I've tested it with the exact same item and crafttweaker script. The damaged item appears in my inventory after using the recipe.

**Comment by Sixdd6** [comment]
Well that is odd, guess I'll start disecting the modpack to find the culprit. Thank you for the response.

**Comment by Sixdd6** [comment]
After starting a new world the problem has disappeared so I'm not sure what the problem was before.
