### ISSUE TITLE
Error in examplemod

### ISSUE THREAD

**Issue by Sixdd6** [cubex2/customstuff4#35]
When trying to use the example recipe for ShapedDamageable I get this error

IllegalStateException: Not a JSON Object: "XXX"

This is referring to the "pattern" part of the recipe.

**Comment by cubex2** [comment]
Can you provide the complete recipe file you're using?

**Comment by Sixdd6** [comment]
That's just using the example recipe file from the examplemod here on GitHub. [My Recipe](https://gist.github.com/Sixdd6/e588c138d0f3eb4323d66bcaca0f5709)
[The example recipe](https://github.com/cubex2/customstuff4/blob/master/examplemod/assets/cs4examplemod/recipes/damage_shaped.json)

**Comment by cubex2** [comment]
It should be "pattern" instead of "shape".

**Comment by Sixdd6** [comment]
actually I found that and tried it, I got the same error. Forgot to post it here.

**Comment by cubex2** [comment]
You recipe is exactly the same as the example, so it can't be incorrect. Where did you put your recipe file?

**Comment by Sixdd6** [comment]
I have it in its own file called recipes.json, link incoming...

**Comment by Sixdd6** [comment]
Ok, yeah I had the recipe.json in the wrong folder apparantly. It's working fine now.
