### ISSUE TITLE
Help needed with IMC

### ISSUE THREAD

**Issue by Sixdd6** [cubex2/customstuff4#36]
I'm having trouble getting the IMC support for the oven in Cooking for Blockheads working with an item from custom stuff 4. If I could get an example of a working IMC json I'd really appreciate it. [Here is the CFB github](https://github.com/blay09/CookingForBlockheads)

**Comment by Sixdd6** [comment]
Ok, I figured out I need to use the nbt type but I can't for the life of me figure out how to format the values correctly. This is what I have so far, I know it's an nbt formatting issue but I can't find any help on how to do the formatting.  [What I have so far](https://gist.github.com/Sixdd6/d50cd2e127ba89e026805266ef957481)

**Comment by Sixdd6** [comment]
Ok, I figured out the nbt formatting finally (I think) but I still cannot get this to work. Is [this](https://gist.github.com/Sixdd6/d50cd2e127ba89e026805266ef957481) correct?

**Comment by cubex2** [comment]
It should look like [this](https://pastebin.com/KXXp3TRV).

**Comment by Sixdd6** [comment]
OMG Thank you very much! Now that I have a working example the rest should be easy enough.
