### ISSUE TITLE
Issue creating machine

### ISSUE THREAD

**Issue by Sixdd6** [cubex2/customstuff4#38]
I'm trying to create a simple machine that runs without fuel but I keep getting issues. For one the machine doesn't run even though I have fuelSlots set to 0. I assume the recipes are setup properly since they show in JEI. I'm also getting [this crash](https://pastebin.com/egd3HKt4) when I try to shift-click an item "out" of the input slot.

The file is I'm having trouble with is [here](https://github.com/Sixdd6/fantastic-octo-rotary-phone/blob/master/sixddmod/content/apiary.json) I'd really appreciate any help.

**Comment by CastielAngelow** [comment]
Could you remove all mods (including shaders) and repeat same thing without any mods beside Forge+Custom Stuff 4...? Also, crash you included looks like its not real crash report but console log.
Real crash logs are saved at minecraft directory under "crash-reports" file. ;-)

**Comment by cubex2** [comment]
The problem seems to be your shiftClickRules. You use slot 38 but your machine only has 38 slots. Since the slots start with 0, the last slot is 37 in your case.

**Comment by Sixdd6** [comment]
Thanks, I'll try that asap.
