### ISSUE TITLE
Recipe Questions

### ISSUE THREAD

**Issue by Towsty** [cubex2/customstuff4#4]
Is it possible to use the ore dictionary when creating the recipes.

IE:
```
"shape": ["SSS", "SCS", "SSS"],
"items": {
	"S": "ore:itemBeeswax",
	"C": "ore:nuggetGold"
}
```

Also I am having an issue with meta data in the recipes. I'd like the above recipe result to give tngtools:itemCast:0 but not sure what is the correct syntax for that.

```
"result": {
	     "item": "tngtools:itemCast@0"
	     "amount": 1
	},
	"mirrored": false

**Comment by Towsty** [comment]
Okay, I figured out the meta thing - for anyone who's curious you don't specify the 0 indexed item only 1 and up. So just use the item name.

**Comment by cubex2** [comment]
At the moment you can specify the metadata using @ only when using the simple format:
```
"result": "tngtools:itemCast@0"
```
If you need to use the longer format you do it like this:
```
"result": {
    "item": "tngtools:itemCast",
    "metadata": 0
}
```

The default metadata is 0 anyway, so it's not necessary to specify it.
I'm going to allow the @ notation in the longer format in the next update.

**Comment by Towsty** [comment]
Awesome thanks, any thoughts on using the oredictionary in recipes?

**Comment by cubex2** [comment]
You can use them just like in your example above.
