### ISSUE TITLE
How to use the mod

### ISSUE THREAD

**Issue by rashard1** [cubex2/customstuff4#40]
I need help figuring out how to use this mod. I don't even know the GUI button to press.

**Comment by CastielAngelow** [comment]
Hi, as far as I come across this mod and start to learning it, there is wiki up above in "hotbar".
(Code / Issues / Pull Request / ... / Wiki)...
There is file folder inside Github repo called "Example Mod". Watch it yourself, download it and learn from it. Beside that from what I understood, you need to create file called "main.json" which is actually somewhat like "modname.class" when you writing real mod. That means all execute things should go there. For example, you need to tell in this file what files you want to include in final pack. Can be wrong, but that is what I understood so far...
