### ISSUE TITLE
Texture pathing does not working

### ISSUE THREAD

**Issue by CastielAngelow** [cubex2/customstuff4#41]
Got a problem that is actually big issue for me. I can't bind texture for block I made.
My "mod" is called **craftweaks**, I added path like this
**...\mods\CRAFTWEAKS\assets\craftweaks\textures\blocks\ct_block_basic.png**.
Also, in JSON file I did this:
```
{
  "blocks": [
    {
      "type": "block:simple",
      "entries": [
        {
          "id": "ct_block_basic",
          "creativeTab": "craftweaks",
          "material": "iron",
          "subtypes": [0, 1],
          "itemModel": {
            "0": "craftweaks:ct_block_basic",
            "1": "craftweaks:block_iron_lapis"
          },
          "hardness": {
            "0": 1,
            "1": 1
          }
        }
      ]
    }
  ]
}
```
I am kinda obssessed, because it just doesn't work. And I made actually everything same as it is in your Example Mod. I only changed textures and textures name... Not sure if its bug or what, but game load normally.

**Comment by cubex2** [comment]
How does your blockstate and model files look like?

**Comment by CastielAngelow** [comment]
Picture : https://i.imgur.com/NDeOKLJ.png

Blockstate folder is empty.

**Comment by CastielAngelow** [comment]
Okay. Does not work at all either. Still "broken" textures on my side. So, here is everything I did:

**blocks.json file:**
```
{
  "blocks": [
    {
      "type": "block:simple",
      "entries": [
        {
          "id": "ct_block_basic",
          "creativeTab": "craftweaks",
          "material": "iron",
          "subtypes": [0, 1],
          "itemModel": {
            "0": "craftweaks:ct_block_basic",
            "1": "craftweaks:ct_block_basic"
          },
          "hardness": {
            "0": 1,
            "1": 1
          }
        }
      ]
    }
  ]
}
```
**main.json file:**

```
{
  "content": [
    {
      "type": "toolTip",
      "entries": [
        {
          "item": "minecraft:coal",
          "text": ["Hold SHIFT..."],
          "mode": "noShift"
        },
        {
          "item": "minecraft:coal",
          "text": ["Tooltip test", "...Or not?"],
          "mode": "shift"
        }
      ]
    },
    {
      "type": "creativeTab",
      "entries": [
        {
          "id": "craftweaks",
          "icon": "craftweaks:ct_block_basic"
        }
      ]
    },
	{
      "file": "blocks.json"
    },
    {
      "type": "fluidModifier",
      "entries": [
        {
          "block": "minecraft:flowing_water",
          "canCreateSource": false
        },
        {
          "block": "minecraft:flowing_lava",
          "canCreateSource": true
        }
      ]
    }
	]
}
```
**ct_block_basic.json file:**
```
> 
> {
>   "variants": {
> 	"subtype=subtype0": {"model": "craftweaks:ct_block_basic"},
> 	"subtype=subtype1": {"model": "craftweaks:ct_block_basic"}
>   }
> }
```

**Comment by CastielAngelow** [comment]
OKAY. STILL DOES NOT WORK. I DID EVERYTHING EXACTLY AS YOUR SAMPLEMOD IS...
There is .zip file with content of my "craftweaks" mod folder inside cs4mod folder. Please, HELP :-(

[CRAFTWEAKS.zip](https://github.com/cubex2/customstuff4/files/1449673/CRAFTWEAKS.zip)

**Comment by CastielAngelow** [comment]
Before I changed some things (code found in zip above):
![2017-11-07_11 58 59](https://user-images.githubusercontent.com/4474447/32490811-caa6d53e-c3b4-11e7-8175-28fa8f6b2a83.png)
After I changed some things(Code you can find here)(
[CRAFTWEAKS.zip](https://github.com/cubex2/customstuff4/files/1449731/CRAFTWEAKS.zip)
):
![2017-11-07_12 11 12](https://user-images.githubusercontent.com/4474447/32490812-cac71cd6-c3b4-11e7-968d-89d0b35d18ac.png)

**Comment by cubex2** [comment]
Your block model is incorrect. The item model doesn't even exist, the file is named "sensor_iron" instead of "ct_block_basic".
