### ISSUE TITLE
Bug? Golden sensors everywhere in my world

### ISSUE THREAD

**Issue by Intipablo** [cubex2/customstuff4#51]
After installing the update I simply downloaded the example mod folder from this GitHub and placed it in my mods folder. (This issue was actually in the old example mod as well) Now every new chunk generated in my world (And new worlds) is filled with golden sensors from the example mod. Any ideas for why this might be happening?

![2018-01-23_01 35 09](https://user-images.githubusercontent.com/19776887/35226091-592137ae-ffde-11e7-83fe-4f8a2b41bbf5.png)

There don't seem to be any errors in my latest.log or any relevant ones in my fml-client-latest.log

**Comment by cubex2** [comment]
This is not a bug. The example mod contains a world gen that generates these blocks in the air. The example mod is not to be played with, it just shows what you can do with the mod.

**Comment by Intipablo** [comment]
Thank you, this is my bad. I wasn't intending on playing with the example mod either..
