### ISSUE TITLE
Example mod doesn't load.

### ISSUE THREAD

**Issue by ZeroLevels** [cubex2/customstuff4#60]
I placed the **examplemod** folder in the mods folder.  They (besides the customstuff4 mod) were the only things in the **mods** folder.  I even tried deleting the **cs4mod** folder and letting it regenerate itself.  Even after regenerating itself, it will not run on second load.  The following error is what I get:

https://pastebin.com/nHU9hXF6

**Comment by cubex2** [comment]
The examplemod on github contains stuff that isn't included in current release. I should probably prevent that after the next release. In the meantime download it from [here](https://github.com/cubex2/customstuff4/tree/3b85bc0e7f708eed48cc80782d770532a3596495)

**Comment by ZeroLevels** [comment]
Tanks, pal. :)
