### ISSUE TITLE
[Request] Non-cubic bounding boxes?

### ISSUE THREAD

**Issue by arfink** [cubex2/customstuff4#63]
Could you please document how to make a block bounding box that is not cubic? EG: rectangular-prism bounding boxes. Thanks!

**Comment by cubex2** [comment]
You can use different values for the `from` or `to` properties like `[0.5, 0.75, 0.5]` to make the bounding box not cubic. I'm not sure what you mean with rectangular-prism.

**Comment by arfink** [comment]
That is exactly what I mean. Thanks. :)
