### ISSUE TITLE
Not sure what I'm doing wrong with recipes.

### ISSUE THREAD

**Issue by ZeroLevels** [cubex2/customstuff4#66]
The below code is what I'm using for some sticks.  The error I get when I start the game is here: 
 https://pastebin.com/4BRn6Mzn

The example recipe provided on the **[Adding Content](https://github.com/cubex2/customstuff4/wiki/Adding-Content)** page works fine, and I was using that as a template... 

Sorry for creating an issue here.  Not sure where I should ask.
```
{
  "content": [
    {
      "type": "shapedRecipe",
      "entries": [
        {
          "shape": ["P", "P"],
          "items": {
            "P": "minecraft:planks@1"
          },
          "result": "zltweaks:stick"
        },{
          "shape": ["P", "P"],
          "items": {
            "P": "minecraft:planks@2"
          },
          "result": "zltweaks:stick@1"
        },{
          "shape": ["P", "P"],
          "items": {
            "P": "minecraft:planks@3"
          },
          "result": "zltweaks:stick@2"
        },{
          "shape": ["P", "P"],
          "items": {
            "P": "minecraft:planks@4"
          },
          "result": "zltweaks:stick@3"
        },{
          "shape": ["P", "P"],
          "items": {
            "P": "minecraft:planks@5"
          },
          "result": "zltweaks:stick@4"
        }
      ]
    }
  ]
}

**Comment by cubex2** [comment]
You need to use minecraft's recipe system to add recipes for the crafting table as mentioned on [Crafting Recipes](https://github.com/cubex2/customstuff4/wiki/Crafting-Recipes).

**Comment by ZeroLevels** [comment]
Hmm.  I tried that earlier and I couldn't get a single recipe to work.  I'll try again and see how it works out.

**Comment by ZeroLevels** [comment]
So the below file "**spruce_stick.json**" placed in **assets/zltweaks/recipes** doesn't seem to work.  Am I supposed to copy the style of json mojang uses in their recipes folder, because it's pretty much a copy/paste of their stick file, just with an additional plank for 6 sticks so as not to possibly conflict with the vanilla recipe.  I tried also replacing **crafting_shaped** with **minecraft:crafting_shaped**, but nothing there either.
```
{
  "type": "crafting_shaped",
  "pattern": [
    "#",
    "#",
    "#"
  ],
  "key": {
    "#": {
      "item": "minecraft:planks",
      "data": 1
    }
  },
  "result": {
    "item": "zltweaks:stick",
    "count": 6
  }
}

**Comment by cubex2** [comment]
It should definitely be **minecraft:crafting_shaped**. I tested the exact same recipe and just used another result item and it worked. That means the recipe is correct. Is there anything in the log file?

**Comment by ZeroLevels** [comment]
I think I'm just too used to crafttweaker.  I didn't include the data tag for the result and I just couldn't figure that I needed it.  My error. **-.-**
