### ISSUE TITLE
Problem with block

### ISSUE THREAD

**Issue by HurtsAsHell** [cubex2/customstuff4#67]
i created a block but the game doesn't charge the texture, what's the problem?

>**models**
{
  "parent": "block/orientable:directional",
  "textures": {
    "textures":"all": "btt:block/star_block"
 }

> **block.json**
{
  "blocks": [
    {
      "type": "block:simple",
      "entries": [
        {
			"id": "ns_block",
			"model": "btt/block:ns_block",
			"material": "iron",
			"creativeTab": "buildingBlocks",
			"maxStack": 64,
			"hardness":1,
			"resistance":1,
			"isBeaconBase" : true,
			"harvestTool": pickaxe,
			"harvestLevel": 3,
			"canPlaceOnCeiling": true,
			"canPlaceOnFloor": true,
			"canPlaceOnSides": true,
			"renderLayer": "solid",
			"faceBySide" : false
		}
	]}
]}

> **main**
{
  "content": [
    {
	"file": "item.json"
	},
	{
	"file": "block.json"
	}
  ]
}

[This is the problem](https://imgur.com/a/X80vr)

Can u help me?

**Comment by cubex2** [comment]
You have to create a blockstate file in assets/btt/blockstates named ns_block.json with the following content:
```json
{
  "variants": {
    "normal": {"model": "btt:ns_block"},
    "inventory": {"model": "btt:ns_block"}
  }
}
```

The model file should look like this:
```json
{
    "parent": "block/cube_all",
    "textures": {
        "all": "btt:blocks/star_block"
    }
}
```

You don't need the **model** property in your block file, it doesn't exist. The used models are defined in the blockstates file mentioned above.
