### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HurtsAsHell** [cubex2/customstuff4#68]
Can i create a mob ?

**Comment by cubex2** [comment]
This is currently not possible.

**Comment by HurtsAsHell** [comment]
do you think you can do it in this version? would be great

**Comment by cubex2** [comment]
At some point I may be adding this but there's alot of other things I'm going to work on first.

**Comment by HurtsAsHell** [comment]
:S PLEASE ADDD ahah; Okay, I understand

**Comment by cubex2** [comment]
Like [here](https://github.com/cubex2/customstuff4/blob/master/examplemod/main.json#L92-L105).

**Comment by HurtsAsHell** [comment]
okay, thanks;  can u add this things in the wiki?

**Comment by HurtsAsHell** [comment]
The default metadata is 1?

**Comment by cubex2** [comment]
Default is 0.

**Comment by HurtsAsHell** [comment]
okay; thanks
