### ISSUE TITLE
Smelting recipes not working?

### ISSUE THREAD

**Issue by Moderocky** [cubex2/customstuff4#69]
Hi,
I followed the Minecraft format for making a smelting recipe (as with crafting recipes) and it says that the minecraft:smelting type isn't valid.
There are no examples for using the customstuff4:smeltingRecipe type, so I don't know how to format that.

`{
  "type": "minecraft:smelting",
  "ingredient": {
    "item": "minecraft:dirt"
  },
  "result": "minecraft:coal",
  "experience": 0.1,
  "cookingtime": 200
}`
This seems logical, but it just gives me an error.

`{
  "type": "customstuff4:smeltingRecipe",
  "input": "minecraft:dirt",
  "result": {
    "item": "minecraft:coal",
    "amount": 1
  },
  "xp": 0.1,
  "cookingtime": 200
}
`
This is "valid" according to Forge, but does nothing.

Which are we supposed to use?

**Comment by ExDomino** [comment]
CustumStuff was never able to add custum recipes in the game, and I used it on many versions : 1.5.2, 1.6.4, 1.7.10. Never I could figure out why my recipes didn't work. Create an item or a block is possible, but configure a recipe is almost impossible or very bad documented. I always had to use MineTweaker (or CraftTweaker) to add my mod recipes in the game.

Now, again after hours trying to figure out why my recipes don't work, I will give up and install CraftTweaker!

**Comment by cubex2** [comment]
You can't use the Minecraft format for anything but crafting recipes. You have to add them the same way you add blocks or items as is shown [here](https://github.com/cubex2/customstuff4/blob/master/examplemod/main.json#L21-L29).
