### ISSUE TITLE
SMP Crash

### ISSUE THREAD

**Issue by Towsty** [cubex2/customstuff4#7]
Custom Stuff 4 v0.0.5
Crash Report (server):
https://gist.github.com/Towsty/845a143cf09e72b04d63cebb4c0b4aca

FML Log:
https://gist.github.com/Towsty/52ee860b57471eba736a34f2e7958194 (make sure to view full file, gist truncates)

**Comment by Towsty** [comment]
On server load with latest version

I've attached my jsons if you need them

[cs4mod.zip](https://github.com/cubex2/customstuff4/files/1036581/cs4mod.zip)

**Comment by cubex2** [comment]
Should be fixed now.
