### ISSUE TITLE
Pre 1.12 recipe style

### ISSUE THREAD

**Issue by arfink** [cubex2/customstuff4#77]
Can we use the pre-1.12 recipe style you list here if it's for a non-vanilla crafting block/table/thing?
https://github.com/cubex2/customstuff4/wiki/Crafting-Recipes

I'd like to be able to make recipes with an arbitrary NBT output, but the 1.12 vanilla recipe format will not allow for this.

**Comment by cubex2** [comment]
You can use that recipe style for anything but the vanilla crafting table. In fact, you have to use it.

**Comment by arfink** [comment]
Excellent, thank you very much.
