### ISSUE TITLE
Technic Launcher

### ISSUE THREAD

**Issue by HurtsAsHell** [cubex2/customstuff4#79]
I created a zip where I uploaded all the files;
Downloaded from the technic launcher and started the modpack, the mod is not displayed and so I can not play with my friends
[https://imgur.com/a/tuF0GOy](url)

**Comment by cubex2** [comment]
Is the zip actually in the mods folder? If yes, did you zip the contents of your mod's folder or the folder itself.

**Comment by cubex2** [comment]
You may need to zip the contents of the custom mod folder. In the recent versions of forge, it will no longer load mods from folders which might be why it doesn't work.

**Comment by HurtsAsHell** [comment]
ci provo e ti informo se funziona

**Comment by HurtsAsHell** [comment]
I'll try and let you know if it works

**Comment by HurtsAsHell** [comment]
with the zip the pack goes into error and does not start [https://pastebin.com/CXEhdbdT](url)
looking at the screen sent, I have to add more?

**Comment by cubex2** [comment]
Can you upload the custom.zip file for me to see.

**Comment by HurtsAsHell** [comment]
[https://www.dropbox.com/s/ii51xmixnhsdgez/BeforeTheThechnology.zip?dl=1](url)

**Comment by HurtsAsHell** [comment]
This is another problem [https://imgur.com/a/X5FZRAT](url) but I do not think it's due to your mod or it could create problems for the mod; in any case, do you know what could be due?

**Comment by cubex2** [comment]
You need to zip the contents of the _Custom_ folder not the folder itself. The top level folders/files in the zip should be _assets_, _cs4mod_, _cs4mod.json_, etc.

The other issue seems to be caused by one of your tweaker scripts.

**Comment by cubex2** [comment]
[This](http://www.mediafire.com/file/glu1ikzad6r93pd/cs4examplemod.zip) is how the zip looks for the example mod.

**Comment by HurtsAsHell** [comment]
I solved, just put in a zip all the contents of the custom folder; Thanks
