### ISSUE TITLE
[COL] with forge 2678, cs4 0.5.2

### ISSUE THREAD

**Issue by drakray** [cubex2/customstuff4#82]
Crashlog
https://pastebin.com/mTGagqPc

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Drakray's Custom Stuff (drakraystuffs)
Caused by: java.lang.ClassNotFoundException: cs4mod.drakraystuffs
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
```

zipped mod
https://www.dropbox.com/s/jj5i3y1pghp3vse/drakraystuffs.zip?dl=0
contain 1 block:orientable:directional, with custom model
any idea why is that?

**Comment by cubex2** [comment]
The zip file should not contain the `drakraystuffs` folder but only its contents. The top level folders should in the zip should be `assets`, `cs4mod`, etc.

**Comment by drakray** [comment]
ok, thank, i'll try that
