### ISSUE TITLE
problem making stairs

### ISSUE THREAD

**Issue by Varg95** [cubex2/customstuff4#84]
I can't seem to make stairs with my own blocks ("modelState": {
		"block": "gaia:adamant",
		"properties": {
		"variant": "normal"
		} ) 
or even other stuff as minecraft:log variant:spruce. This is the crashlog i get https://pastebin.com/eaWYrnKt

**Comment by cubex2** [comment]
What type of block is `gaia:adamant`? No block created with CS4 should have a `variant` property. If it's just a regular block, you should remove the `properties` attribute completely.
