### ISSUE TITLE
Crash with simple mod, help?

### ISSUE THREAD

**Issue by Malus-Lupo** [cubex2/customstuff4#97]
Can nay one help me figure out why I keep getting this crash, I am only adding 2 food items so far. I included a zip with my files in and the crash.

Thanks in advanced!
[crash-2018-09-26_11.57.05-client.txt](https://github.com/cubex2/customstuff4/files/2420543/crash-2018-09-26_11.57.05-client.txt)
[My Mod.zip](https://github.com/cubex2/customstuff4/files/2420544/My.Mod.zip)

**Comment by RobinNightWing** [comment]
I know its almost a year now, but why is your file a jar file

**Comment by Malus-Lupo** [comment]
I honestly do not know the answer to that question, or if it should or should not be a jar, I ended up adding new foods with ContentTweaker, as I had not found it yet but when I did realized I was already using a lot of the scripts for my pack and it fit better. Sorry.
